[build]
  command = "echo No build needed"
  functions = "functions"
  publish = "public"

[functions]
  external_node_modules = ["express", "ejs", "serverless-http"]
  included_files = ["views/**", "public/**"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true